<h1 style='color:blue;' align='center'>KFold Cross Validation Python Tutorial</h2>

In [1]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets
import pandas as pd

In [2]:
iris = datasets.load_iris()

In [3]:
dir(iris)

['DESCR',
 'data',
 'data_module',
 'feature_names',
 'filename',
 'frame',
 'target',
 'target_names']

In [4]:
df = pd.DataFrame(iris.data, columns = iris.feature_names)
df['target'] = iris.target
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   target  
0       0  
1       0  
2       0  
3       0  
4       0

In [5]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(iris.data,iris.target,test_size=0.2)

**Logistic Regression**

In [6]:
lr = LogisticRegression()
lr.fit(x_train, y_train)
lr.score(x_test, y_test)

1.0

**SVM**

In [7]:
svm = SVC()
svm.fit(x_train, y_train)
svm.score(x_test, y_test)

0.9666666666666667

**Random Forest**

In [8]:
rf = RandomForestClassifier(n_estimators=40)
rf.fit(x_train, y_train)
rf.score(x_test, y_test)

1.0

<h2 style='color:purple'>cross_val_score function</h2>

In [9]:
from sklearn.model_selection import cross_val_score

**Logistic regression model performance using cross_val_score**

In [10]:
lr_score = cross_val_score(LogisticRegression(), iris.data, iris.target)
lr_score

C:\Users\Mark Vincent\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


array([0.96666667, 1.        , 0.93333333, 0.96666667, 1.        ])

In [11]:
np.average(lr_score)


0.9733333333333334

**svm model performance using cross_val_score**

In [12]:
svm_score = cross_val_score(SVC(),iris.data, iris.target)
svm_score

array([0.96666667, 0.96666667, 0.96666667, 0.93333333, 1.        ])

In [13]:
np.average(svm_score)


0.9666666666666666

**DecisionTree performance using cross_val_score**

In [14]:
Dt_score = cross_val_score(DecisionTreeClassifier(),iris.data, iris.target)
Dt_score

array([0.96666667, 0.96666667, 0.9       , 0.96666667, 1.        ])

In [15]:
np.average(Dt_score)


0.9600000000000002

**random forest performance using cross_val_score**

In [16]:
rf_score = cross_val_score(RandomForestClassifier(n_estimators=100),iris.data, iris.target)
rf_score

array([0.96666667, 0.96666667, 0.93333333, 0.93333333, 1.        ])

In [17]:
np.average(rf_score)


0.96

<h2 style='color:purple'>Exercise</h2>

Use iris flower dataset from sklearn library and use cross_val_score against following
models to measure the performance of each. In the end figure out the model with best performance,
1. Logistic Regression
2. SVM
3. Decision Tree
4. Random Forest